> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "bboomm63/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/bboomm63/numpy-array-operations


'https://jovian.ai/bboomm63/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

# List of functions explained 

>function1 = np.concatenate(arr1, arr2)<br>
 -join the arrays by axes

>function2 = arr.reshape(4, 3)<br>
 -reshape the array into 4x3 form of array

>function3 = np.where(arr == 4)<br>
 -returns the indexes that matches the given value

>function4 = random.randint(n)<br>
 -generates a random value that ranges from 0 to n

>function5 = random.normal(loc, scale, size)<br>
 -loc =mean<br>
 -scale = standard deviation<br>
 -size = the shape of returned array<br>

## Function 1 - np.concatenate

Add some explanation about the function in your own words

In [29]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis = 1)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [8., 9.]])

Explanation about example

In [27]:
# Example 2 - working
arr1 = [[1, 2],
       [3, 4], 
       [5, 6]]

arr2 = [[11, 22], 
       [33, 44]]

np.concatenate((arr1, arr2), axis = 0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [11, 22],
       [33, 44]])

Explanation about example

In [18]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

When axis = 0, the size of size of the arrays must match.

For those who might be confused, the value of axis refers to the direction of which the arrays would be joined.
If axis = 0, the arrays will be stacked vertically and if axis = 1, the arrays would be aligned horizontally.

In [30]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "bboomm63/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/bboomm63/numpy-array-operations


'https://jovian.ai/bboomm63/numpy-array-operations'

## Function 2 - np.reshape

It literally reshapes the array.

In [35]:
# Example 1 - working
arr = np.array([[1, 2, 3],
               [4, 5, 6]])

arr.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

Explanation about example

In [39]:
# Example 2 - working
arr = np.array([[[1, 2], [3, 4]],
               [[5, 6], [7, 8]],
               [[9, 10], [10, 11]]])
arr.reshape(2, 2, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 10, 11]]])

Explanation about example

In [40]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr.reshape(3, 3)

ValueError: cannot reshape array of size 6 into shape (3,3)

When reshaping an array, the size of the array must be consistent.

In [41]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "bboomm63/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/bboomm63/numpy-array-operations


'https://jovian.ai/bboomm63/numpy-array-operations'

## Function 3 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

## Function 4 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

## Function 5 - ???

Add some explanations

In [ ]:
# Example 1 - working
???

Explanation about example

In [ ]:
# Example 2 - working
???

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
???

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()